# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jsonrepair < Formula
  desc "🔧 Repair JSON! Solution for JSON Anomalies from LLMs"
  homepage "https://github.com/RealAlexandreAI/json-repair"
  version "0.0.3"
  license "GPLv3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/RealAlexandreAI/json-repair/releases/download/v0.0.3/jsonrepair_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "642cd9eb35b9845840b834fb5b6e25cbbd023df8173b0c1b7aca87523b32ea1b"

      def install
        bin.install "jsonrepair"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/RealAlexandreAI/json-repair/releases/download/v0.0.3/jsonrepair_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "6255665ec46cf8a1ba1b82e193c5633a3ca2b7ce383585256fea370f4241daed"

      def install
        bin.install "jsonrepair"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/RealAlexandreAI/json-repair/releases/download/v0.0.3/jsonrepair_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "32d7429f5e374fea41e562df624f27d425cfc1fe49f2f86b4eb1f21e442d856f"

      def install
        bin.install "jsonrepair"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/RealAlexandreAI/json-repair/releases/download/v0.0.3/jsonrepair_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "953e0b9d55a64022987c0252dcb7a5f0c89d45bdcd24354e48e5aeea0d289173"

      def install
        bin.install "jsonrepair"
      end
    end
  end

  test do
    system "#{bin}/jsonrepair -v"
  end
end
